### ISSUE TITLE
[Tracking] set up v0.1 dbt

### ISSUE THREAD

**Issue by ran-codes** [Drexel-UHC/hcup-dbt#1]
initialize a duckdb-dbt project and generate prototype models!

## Action items
- [x] #2
- [x] #3 
- [x] Deploy dbt documentation to [gh-pages](https://drexel-uhc.github.io/hcup-dbt/)
- [x] set up test model to check `prod` on UHC desktop
- [x] #5
- [x] #4
- [x] Add macros documentation
- [x] #6

**Comment by ran-codes** [comment]
set up done. I think v0.1 is looking great!
