### ISSUE TITLE
[HCUP 'marts' brainstorm + limit testing]

### ISSUE THREAD

**Issue by ran-codes** [Drexel-UHC/hcup-dbt#9]
The final product of DBT is a set up of business-use/research-specific tables;  products are what end-users access to do their research, power their dashboards ... ETC. Importantly, the type and complexity the end tables aka `marts` will determine ultimately how our project (source > staging/base models > intermediate models > end-tables/mart models) is organized. So for us to start building we need to get an idea of what the end tables will be. So it would be very useful for end users to brainstorm what type of `final-product tables` they would like: both simple analytic tables and some fancy stuff (e.g. you want  some imputations).

Really want to get a good idea of some simple/complex use cases to develop and limit test this DBT system. 

[marts_log.xlsx](https://github.com/Drexel-UHC/hcup-dbt/files/11202197/marts_log.xlsx)
![image](https://user-images.githubusercontent.com/45013044/231237867-75874db7-e915-4af8-81d3-8a813e9fdba9.png)

### Action Items

- [x] Drexel-UHC/hcup-extraction-loading#23 
- [x] Drexel-UHC/hcup-dbt#19 
- [ ] Drexel-UHC/hcup-dbt#20 
- [ ] Drexel-UHC/hcup-dbt#17 
- [ ] Drexel-UHC/hcup-dbt#18

**Comment by usamabilal** [comment]
Probably overlapping with Alina, but some of these would be useful top of my head. I don't know HCUP very well yet so I may be wrong, feel free to correct @alinasmahl1 

- # of unique patients visiting the ER with a flu ICD code (@alinasmahl1 ? some common definition?) by week and city
- # of unique patients visiting the ER with a flu ICD code by ZCTA (and city)
- # of ER visits with a flu ICD code by ZCTA (and city)
- # of ER visits with a flu ICD code by race/ethnicity and city

**Comment by alinasmahl1** [comment]
Thanks @usamabilal -- one note, I think we have month not week in HCUP. HCUP is an encounter level file, but I think there's a separate file for readmissions-- so we'd hav eot pull in that readmission identifier for the patient-level databases. 

I think we'd also want the following kinds of tables. 

- Number of Inpatient (IP) Flu and ILI visits by race/ethnicity and urbanicity
- Cost of IP Flu and Ili visits by city
- Number of IP flu and ILI visits by hospital and race/ethnicity and other by hospital and line of business (e.g. medicaid, medicare, commercial, uninsured) 
- for all the above tables, I'd think we want to include population estimates as well. is that something we'd want to include in the dbt layer? 
- we could theoretically do some sort of imputation for missing Race/ethnicity (say using zcta data-- i'm genearlly not a fan of this appraoch, but just as an example use case). 

Based on putting this together, I'm thinking that the marts should be determined by the level- e.g. individual, zcta, city/county, hospital, as well as whatever modifiers we'll want to consider (race/ethnicity, age, age *race-ethnicity, gender, age* race ethnicity * gender). As well as which data tables things come from (e..g main HCUP vs the cost one).

**Comment by alinasmahl1** [comment]
@ran-codes I think to include additional variables in the initial data models. Can we please include the following variables? "AGE", "YEAR", "ZIP", "ZIP3", "VisitLink", "CPT1", "CPT2", "CPT3", "CPTCCS1",
   "CPTCCS2", "DHOUR",  "DMONTH", "DQTR" "DRG". "DISP_X", "DISPUB04", "DMONTH", "DQTR", "DSHOSPID", "HCUP_ED",
   "HCUP_OS", "HOSPST", "I10_DX_Visit_Reason1", "I10_DX_Visit_Reason2", "I10_DX1",
       "I10_DX2", "LOS", "PSTCO", "PSTCO2","HISPANIC", "RACE", "ZIPINC_QRTL", "PAY1", "DIED", "FEMALE", "HOSP_NPI", " 
     "I10_DX_Admitting"

**Comment by ran-codes** [comment]
>HCUP is an encounter level file, but I think there's a separate file for readmissions-- so we'd hav eot pull in that readmission identifier for the patient-level databases.

@alinasmahl1 do we have these readmision files?

**Comment by alinasmahl1** [comment]
what time level do we want all these tables at: month-year, or just year?

@ran-codes  month year please
do we have these readmision files?
@ran-codes 
it looks like the var VisitLink identifies readmissions. Here's the website with info on what years/states include the Visitlink var 

https://hcup-us.ahrq.gov/db/vars/siddistnote.jsp?var=visitlink

do you mean average discharge level cost or total?
@ran-codes ah yup I do- I think average discharge is a good place to start.

**Comment by ran-codes** [comment]
All v0.2 mart items done. please see gh-pages for documentation: https://drexel-uhc.github.io/hcup-dbt/#!/overview

**Comment by alinasmahl1** [comment]
@ran-codes going through data and realized we don't have NY 2009 or 2010 SID or SEDD included in dbt. Can we please add?

**Comment by ran-codes** [comment]
got it! added to v0.3 seed/source to-do (see #26)

**Comment by alinasmahl1** [comment]
thanks!
